# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parameters.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'parameters.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10parameters.proto\x12\x0bsvg_builder\"\xb4\x01\n\nParameters\x12\x0c\n\x04seed\x18\x01 \x01(\r\x12#\n\x06output\x18\x02 \x01(\x0b\x32\x13.svg_builder.Output\x12+\n\nbackground\x18\x03 \x01(\x0b\x32\x17.svg_builder.Background\x12\x1f\n\x04icon\x18\x04 \x01(\x0b\x32\x11.svg_builder.Icon\x12%\n\x07overlay\x18\x05 \x01(\x0b\x32\x14.svg_builder.Overlay\"\x87\x01\n\x06Output\x12!\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x11.svg_builder.FileH\x00\x12%\n\x06stdout\x18\x02 \x01(\x0b\x32\x13.svg_builder.StdoutH\x00\x12+\n\tdirectory\x18\x03 \x01(\x0b\x32\x16.svg_builder.DirectoryH\x00\x42\x06\n\x04sink\"(\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x12\n\nresolution\x18\x02 \x01(\t\"\x1c\n\x06Stdout\x12\x12\n\nresolution\x18\x01 \x01(\t\".\n\tDirectory\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x13\n\x0bresolutions\x18\x02 \x03(\t\"\xc7\x01\n\nBackground\x12.\n\x06motion\x18\x01 \x01(\x0e\x32\x1e.svg_builder.Background.Motion\x12,\n\x05image\x18\x02 \x01(\x0e\x32\x1d.svg_builder.Background.Image\"9\n\x06Motion\x12\n\n\x06STATIC\x10\x00\x12\x08\n\x04SCAN\x10\x01\x12\n\n\x06LIGHTS\x10\x02\x12\r\n\tCLOSEOPEN\x10\x03\" \n\x05Image\x12\x08\n\x04NONE\x10\x00\x12\r\n\tSTARFIELD\x10\x01\"[\n\x04Icon\x12\'\n\x07hexatri\x18\x01 \x01(\x0b\x32\x14.svg_builder.HexatriH\x00\x12!\n\x04ship\x18\x02 \x01(\x0b\x32\x11.svg_builder.ShipH\x00\x42\x07\n\x05glyph\"X\n\x07Hexatri\x12+\n\x06motion\x18\x01 \x01(\x0e\x32\x1b.svg_builder.Hexatri.Motion\" \n\x06Motion\x12\n\n\x06ROTATE\x10\x00\x12\n\n\x06STATIC\x10\x01\"\x06\n\x04Ship\"9\n\x07Overlay\x12%\n\x06matrix\x18\x01 \x01(\x0b\x32\x13.svg_builder.MatrixH\x00\x42\x07\n\x05layer\"&\n\x06Matrix\x12\r\n\x05\x61ngle\x18\x01 \x01(\x01\x12\r\n\x05\x63olor\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parameters_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMETERS']._serialized_start=34
  _globals['_PARAMETERS']._serialized_end=214
  _globals['_OUTPUT']._serialized_start=217
  _globals['_OUTPUT']._serialized_end=352
  _globals['_FILE']._serialized_start=354
  _globals['_FILE']._serialized_end=394
  _globals['_STDOUT']._serialized_start=396
  _globals['_STDOUT']._serialized_end=424
  _globals['_DIRECTORY']._serialized_start=426
  _globals['_DIRECTORY']._serialized_end=472
  _globals['_BACKGROUND']._serialized_start=475
  _globals['_BACKGROUND']._serialized_end=674
  _globals['_BACKGROUND_MOTION']._serialized_start=583
  _globals['_BACKGROUND_MOTION']._serialized_end=640
  _globals['_BACKGROUND_IMAGE']._serialized_start=642
  _globals['_BACKGROUND_IMAGE']._serialized_end=674
  _globals['_ICON']._serialized_start=676
  _globals['_ICON']._serialized_end=767
  _globals['_HEXATRI']._serialized_start=769
  _globals['_HEXATRI']._serialized_end=857
  _globals['_HEXATRI_MOTION']._serialized_start=825
  _globals['_HEXATRI_MOTION']._serialized_end=857
  _globals['_SHIP']._serialized_start=859
  _globals['_SHIP']._serialized_end=865
  _globals['_OVERLAY']._serialized_start=867
  _globals['_OVERLAY']._serialized_end=924
  _globals['_MATRIX']._serialized_start=926
  _globals['_MATRIX']._serialized_end=964
# @@protoc_insertion_point(module_scope)
