//! The schema boundary. `parameters.proto` is the single source of truth for
//! what a config may contain; everything here either comes from it or states a
//! rule proto3 cannot.

// Generated by build.rs: the messages, then the proto3 JSON mapping over them.
// clippy runs over included code same as our own; the generator's output isn't
// ours to fix and is regenerated on every build, so it is exempted here and
// nowhere else -- `parse` below still gets the full lint pass.
#[allow(clippy::all)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/svg_builder.rs"));
    include!(concat!(env!("OUT_DIR"), "/svg_builder.serde.rs"));
}
pub use generated::*;

/// Rejecting a typo'd key, a value of the wrong type and two members of one
/// oneof is the schema's job, so none of it is re-checked here.
pub fn parse(text: &str) -> Result<Parameters, serde_json::Error> {
    serde_json::from_str(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The three rejections that must come from the schema itself rather than
    /// from a hand-written check. If someone later flattens a `oneof` back into
    /// plain fields, or turns unknown-field rejection off, this is what fails.
    #[test]
    fn the_schema_rejects_what_it_cannot_represent() {
        assert!(parse(r#"{"icon":{"ship":{"motion":"ROTATE"}}}"#).is_err());
        assert!(parse(r#"{"overlay":{"angle":90}}"#).is_err());
        assert!(parse(r#"{"output":{"file":{"path":"a.svg"},"stdout":{}}}"#).is_err());
        assert!(parse(r#"{"backgrond":{}}"#).is_err());
        assert!(parse(r#"{"background":{"motion":"SPIRAL"}}"#).is_err());
    }

    /// Every proto3 zero is this program's default, so `{}` is a complete
    /// config: hexatri rotating on a plain static lattice with no overlay.
    #[test]
    fn an_empty_config_is_a_complete_config() {
        let p = parse("{}").expect("{} must parse");
        assert_eq!(p.seed, 0);
        assert_eq!(
            p.background.unwrap_or_default().motion(),
            background::Motion::Static
        );
        assert!(p.icon.is_none());
        assert_eq!(
            parse(r#"{"background":{"motion":"CLOSEOPEN","image":"STARFIELD"}}"#)
                .unwrap()
                .background
                .unwrap()
                .motion(),
            background::Motion::Closeopen
        );
    }
}
